image: rust:latest

default:
  tags:
    - docker

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - "$CARGO_HOME/bin"

before_script:
  - export PATH="$PATH:$CARGO_HOME/bin"
  - mdbook --version || cargo install mdbook mdbook-linkcheck mdbook-mermaid mdbook-emojicodes mdbook-admonish

pages:
  stage: deploy

  script:
    - mdbook build
    - mv book/html public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test

  script:
    - mdbook build

  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

