generate-book:
  stage: build
  image: rust:1.69

  script:
    - cargo install mdbook mdbook-linkcheck mdbook-mermaid mdbook-emojicodes mdbook-admonish
    - mdbook build $BOOK_DIR

  artifacts:
    paths:
      - $BOOK_DIR/book/html
    # make sure GitLab doesn't accidentally keep every book you ever generate
    # indefinitely
    expire_in: 1 week

pages:
  image: busybox:latest
  stage: deploy

  dependencies:
    - generate-book
  script:
    - cp -r $BOOK_DIR/book/html public

  artifacts:
    paths:
      - public

  only:
    - main
