default:
  tags:
    - docker

pages:
  stage: deploy
  image: rust:latest

  script:
    - cargo install mdbook mdbook-linkcheck mdbook-mermaid mdbook-emojicodes mdbook-admonish
    - mdbook build -d public

  artifacts:
    paths:
      - public

  only:
    - main
